### ISSUE TITLE
Y-Axis question

### ISSUE THREAD

**Issue by aussiegingersnap** [jgoerzen/covid19ks#1]
@jgoerzen , thank you for presenting the data here in a new way! (Also Rust <3) 

Question on your Data Science methodology - What went into your decision to use a 7-day MA relative to % increase on the y-axis?

**Comment by jgoerzen** [comment]
Hi,

The 7-day MA was because the original chart which was attacked used that as well.  That is often used because there is always a dip in new cases on the weekend when fewer people go see their doctor or testing is less available/closed.   That weekly dip can make it hard to discern trends.  There can also be situations of results being bunched up and looking like a spike on a certain day.

The counties with masks represent 2/3 of the population of Kansas and are also more urban.  The original chart from KDHE used two different Y-axis scales to try to put the two lines in perspective.  This is what it was unfairly attacked for, and then there were people that said "well looky here, the counties with mask requirements have MORE cases!"  Of course they have more cases.  They have more people.

So this was an attempt to make something with a unified Y-axis to show people.  The start and end dates of the chart highlighted at the top match the KDHE chart for comparison.
